### ISSUE TITLE
Enhancement: Test if prototype has property

### ISSUE THREAD

**Issue by oakley808** [caseycesari/GeoJSON.js#13]
Hi.
I'm using `GeoJSON.parse()` to build geojson from some json objects. Their geometry coordinates are inherited through prototype, and not direct properties of the object itself. This seems to cause `buildGeom()` to fail the hasOwnProperty test (https://github.com/caseypt/GeoJSON.js/blob/master/geojson.js#L128). 
Thus I end up with an empty geometry object.

Is there a workaround for this? If not, would it be possible to pass in a flag to tell parse() to do a for/in check instead of hasOwnProperty check ?

**Comment by caseypt** [comment]
Hey! Thanks for opening this. Sorry for the delay; I was out of town last week. 

I'll take a look this week and see if I can figure out a solution. In the mean time, feel free to submit a PR.

**Comment by caseycesari** [comment]
Closing this as I'm unlikely to implement it, but thanks again for the suggestion.
