### ISSUE TITLE
Use of Promise?

### ISSUE THREAD

**Issue by DemersM** [caseycesari/GeoJSON.js#17]
I wonder if you think that Promise could be usable to increase performance?

For instance if you use Bluebird Promises you could do something like this in the parse function:

```
    objects.forEach(function(item){
      geojson.features.push(getFeature(item, settings, propFunc));
    });

    Promise.all(geojson.features.then(function() {
          ...
    });
```

See: http://bluebirdjs.com/docs/api/promise.all.html

This way getFeature would be called async. You could do the same for every forEach loop. What do you think about it?

**Comment by caseypt** [comment]
Hi @DemersM, thanks opening an issue. I'm not sure I want to add a dependency to the project, but I would be interested in seeing an approach that implements this something like this, especially if it can help with performance. If you have time, feel free to take a shot at it and open a PR. 

Also, I just noticed your other PR that I said I would get to. Sorry I never got around to merging that. I'll try and get to it this weekend.

**Comment by caseycesari** [comment]
Closing because I'm unlikely to implement this, but thanks for the suggestion.
