### ISSUE TITLE
Big GeoJSON data will result slow performance of render

### ISSUE THREAD

**Issue by nc3816** [caseycesari/GeoJSON.js#38]
Hi, 

When I render the polygons on the map in react native, the big GeoJSON data will result in 5-8 seconds delay of the render.

Any suggestion for optimize it?

Thank you!

**Comment by gharibi** [comment]
Well, I believe it pretty much depends on how your code is structured. Could probably put some parts of your code?

**Comment by gharibi** [comment]
Your code seems alright. I tested the API with around 5,000 features and it was rendered in around 500 mili-seconds. How about your ajax call? you can trace the network and see if that is taking time.

**Comment by nc3816** [comment]
@gharibi Thank you! I haven't checked the network, after rendering the polygon, when I drag my map from somewhere to otherwhere, it moves very slowly and you need to wait 6-7 seconds to wait for one move operation finished. So I think the re-render after dragging the map cost much time and it could estimate by seconds.

**Comment by nc3816** [comment]
I solved this problem.
My method is looping the coordinates, remove the points which are not in the view of the current map view. And generate a new Geojson object to render, works well.
Thank you!
