### ISSUE TITLE
May I can open a new repo of this library? It is written in Typescript

### ISSUE THREAD

**Issue by eugeneYWang** [caseycesari/GeoJSON.js#41]
Hi Casey,

I really want to appreciate your ideas and works to come up with this library. I like how simple and intuitive it is to transform an JSON to GeoJSON. 

I am developing web applications in Augular. When I was looking for a feature like this, I found your library in NPM. Usually, I just need to find a type definition file in the official repo of type definition, in order to use a javascript library in TypeScript. However, in the official repo of type definitions, the type definition named as GeoJSON has been occupied for other use. Now no one can contribute a type definition for this library, unless those volunteers of GeoJSON type definition are willing to return it back to you. 

In this situation, I refactored this library in TypeScript to make it available in Angular. I am willing to make it open source but I also want to have your permission. If you are okay, I will open a new repo to share this library in TypeScript. So this functions exists in GeoJSON.

Thanks,

Eugene

**Comment by caseycesari** [comment]
Hi Eugene! Thanks for the message. Yeah, open-sourcing that library sounds good to me!

**Comment by SaltyPotato** [comment]
Hello Eugene, Did you open-source the library?

**Comment by eugeneYWang** [comment]
Hi @SaltyPotato! Thank you for checking out with this post. Because of you, I have finally make myself publish my Typescript version in open source. Because I have not find a way to distribute that TS package/library in Typescript, I have not made it in NPM. But you can find my typescript file in https://github.com/eugeneYWang/GeoJSON.ts

**Comment by eugeneYWang** [comment]
Hi Casey @caseycesari ,

I am here to let you know that I open sourced that TS library, and I keep the name of your library in README and LICENSE. Thank you very much for your support by allowing me to open source it! If there is any thing I have not done properly in the open source way, please feel free to let me know. This is my first open source package, so I might have some mistakes, but I will not forget to respect your innovation.

Best,
Eugene

**Comment by caseycesari** [comment]
Nice job @eugeneYWang! Looks good to me.

**Comment by eugeneYWang** [comment]
@caseycesari Thank you! For the benefits of typescript users, would you mind to add a line of comment in the README of your library so they know my TS version? If you want, I can open a PR and contribute that comment to your README.

**Comment by caseycesari** [comment]
Yeah, feel free to open a PR for that.

**Comment by SaltyPotato** [comment]
> Hi @SaltyPotato! Thank you for checking out with this post. Because of you, I have finally make myself publish my Typescript version in open source. Because I have not find a way to distribute that TS package/library in Typescript, I have not made it in NPM. But you can find my typescript file in https://github.com/eugeneYWang/GeoJSON.ts

Thanks mate! Highly appreciated!

**Comment by eugeneYWang** [comment]
@SaltyPotato It is my great pleasure to be helpful! Thanks for your star, too!

**Comment by eugeneYWang** [comment]
Closed this issue for the typescript version has been set up at https://github.com/eugeneYWang/GeoJSON.ts.
