### ISSUE TITLE
error TS2456: Type alias 'Geometry' circularly references itself.

### ISSUE THREAD

**Issue by aninaA** [caseycesari/GeoJSON.js#57]
Suddenly getting an error while trying to build an angular component with this library: 
ERROR in node_modules/@types/geojson/index.d.ts(79,13): error TS2456: Type alias 'Geometry' circularly references itself.

using https://registry.npmjs.org/@types/geojson/-/geojson-7946.0.10.tgz

**Comment by holdenparker** [comment]
Hi @aninaA!  This library, although named the same, does not correspond with the `@types/geojson` library.  That library can be found [here](https://github.com/DefinitelyTyped/DefinitelyTyped/commits/master/types/geojson).

**Comment by caseycesari** [comment]
Thanks @holdenparker for point @aninaA in the right direction. Going to close this out.
